export default {
    ACTIONS: {
        SAVE_CASE_DATA: 'SAVE_CASE_DATA',
        CLEAR_DATA: 'CLEAR_DATA',
        SELECT_CASE: 'SELECT_CASE',
        UNAUTHORIZED_REQUEST: 'UNAUTHORIZED_REQUEST',
        GENERAL_LOGIN_ERROR: 'GENERAL_LOGIN_ERROR',
        SAVE_APPOINTMENT: 'SAVE_APPOINTMENT'
    },
}