export default {
    ACTIONS: {
        SAVE_NOTIFICATION_DETAIL: 'SAVE_NOTIFICATION_DETAIL',
        CLEAR_DATA: 'CLEAR_DATA',
        UNAUTHORIZED_REQUEST: 'UNAUTHORIZED_REQUEST',
        GENERAL_NOTIFICATION_DETAIL_ERROR: 'GENERAL_NOTIFICATION_DETAIL_ERROR',
        CLEAR_NOTIFICATION_DETAIL: 'CLEAR_NOTIFICATION_DETAIL',
        UPDATE_FIREBASE_NOTIFICATION_ID: 'UPDATE_FIREBASE_NOTIFICATION_ID',
        REMOVE_FIREBASE_NOTIFICATION_ID: 'REMOVE_FIREBASE_NOTIFICATION_ID',
        UPDATE_READ_INFO: 'UPDATE_READ_INFO'
    },
}