export default {
    ACTIONS: {
        SAVE_NOTIFICATION_DATA: 'SAVE_NOTIFICATION_DATA',
        CLEAR_DATA: 'CLEAR_DATA',
        UNAUTHORIZED_REQUEST: 'UNAUTHORIZED_REQUEST',
        GENERAL_NOTIFICATION_ERROR: 'GENERAL_NOTIFICATION_ERROR'
    },
}