let constants = {
    ACTIONS: {
      SAVE_USER_DATA: 'SAVE_USER_DATA',
      LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
      SAVE_LANGUAGE: 'SAVE_LANGUAGE',

    //   RESET_ERROR_MESSAGE: 'RESET_ERROR_MESSAGE',
    //   TOGGLE_LOGIN_MODAL: 'TOGGLE_LOGIN_MODAL',
    //   SHOW_LOGIN_MODAL_SPINNER: 'SHOW_LOGIN_MODAL_SPINNER',
    //   HIDE_LOGIN_MODAL_SPINNER: 'HIDE_LOGIN_MODAL_SPINNER',
    //   UPDATE_CUSTOMER_NAME: 'UPDATE_CUSTOMER_NAME',
    //   VALIDATE_TOKEN_SUCCESS: 'VALIDATE_TOKEN_SUCCESS',
    //   VALIDATE_TOKEN_ERROR: 'VALIDATE_TOKEN_ERROR',
    //   LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    //   LOGIN_ERROR: 'LOGIN_ERROR',
    //   LOGIN_SUCCESS_STORED_CREDENTIALS: 'LOGIN_SUCCESS_STORED_CREDENTIALS',
    //   LOGIN_ERROR_STORED_CREDENTIALS: 'LOGIN_ERROR_STORED_CREDENTIALS'
    },
    TEXTS: {
      HIDE_PASSWORD: 'Hide password',
      SHOW_PASSWORD: 'Show password',
      INVALID_CREDENTIALS: 'Sorry, we couldn’t log you in. Please check your details, and try again.'
    },
    LANGUAGES: {
        ENGLISH : 'en',
        CHINESE: 'zh',
    }
  };
  export default constants;